import { useQuery } from '@tanstack/react-query'
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Download, Sparkles } from 'lucide-react'
import { PageHeader } from '@/components/common/page-header'
import { Button } from '@/components/ui/button'
import { ChartCard } from '@/components/common/chart-card'
import { Card } from '@/components/ui/card'
import { repositories } from '@/services/repositories'
import { LoadingState } from '@/components/common/loading-state'
import { usePageTitle } from '@/hooks/use-page-title'
const fulfillment = [{name:'Week 1',onTime:94.2,accuracy:97.4},{name:'Week 2',onTime:95.1,accuracy:97.8},{name:'Week 3',onTime:96.3,accuracy:98.2},{name:'Week 4',onTime:96.8,accuracy:98.6}]
const supplier = [{name:'Atlas',quality:96,delivery:94},{name:'Nova',quality:91,delivery:96},{name:'Pacific',quality:94,delivery:89},{name:'Vertex',quality:98,delivery:93},{name:'GreenLoop',quality:92,delivery:97}]
export default function AnalyticsPage() { usePageTitle('Analytics'); const { data } = useQuery({ queryKey: ['dashboard', 'analytics'], queryFn: () => repositories.dashboard.getSnapshot() }); if (!data) return <LoadingState/>; const salesSeries = data.salesSeries; return <><PageHeader eyebrow="Intelligence" title="Analytics" description="Explore mock operational, marketplace, fulfillment, and supplier performance insights." actions={<><Button variant="secondary"><Download className="size-4"/>Export dashboard</Button><Button><Sparkles className="size-4"/>Generate insight</Button></>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{l:'Gross merchandise value',v:'$4.92M',h:'+18.4%'},{l:'Fulfillment cycle',v:'2.4 days',h:'-0.6 days'},{l:'Supplier quality',v:'94.8%',h:'+1.2%'},{l:'Forecast accuracy',v:'91.3%',h:'+3.6%'}].map(x=><Card key={x.l} className="p-5"><div className="text-xs font-semibold uppercase tracking-wide text-slate-400">{x.l}</div><div className="mt-3 text-2xl font-bold">{x.v}</div><div className="mt-2 text-xs font-semibold text-emerald-600">{x.h} this period</div></Card>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-2"><ChartCard title="Revenue vs order growth" description="Six-month business performance"><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={salesSeries}><CartesianGrid strokeDasharray="4 4" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis yAxisId="left" axisLine={false} tickLine={false}/><YAxis yAxisId="right" orientation="right" axisLine={false} tickLine={false}/><Tooltip/><Legend/><Line yAxisId="left" dataKey="revenue" stroke="#2563eb" strokeWidth={3} dot={false}/><Line yAxisId="right" dataKey="orders" stroke="#8b5cf6" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></ChartCard><ChartCard title="Supplier scorecard" description="Quality and on-time delivery index"><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={supplier}><CartesianGrid strokeDasharray="4 4" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis domain={[70,100]} axisLine={false} tickLine={false}/><Tooltip/><Legend/><Bar dataKey="quality" fill="#2563eb" radius={[6,6,0,0]}/><Bar dataKey="delivery" fill="#8b5cf6" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></ChartCard></div><div className="mt-5"><ChartCard title="Fulfillment performance" description="On-time fulfillment and order accuracy"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={fulfillment}><CartesianGrid strokeDasharray="4 4" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis domain={[85,100]} axisLine={false} tickLine={false}/><Tooltip/><Legend/><Line dataKey="onTime" stroke="#059669" strokeWidth={3}/><Line dataKey="accuracy" stroke="#2563eb" strokeWidth={3}/></LineChart></ResponsiveContainer></div></ChartCard></div></> }
