import { AlertTriangle, ArrowLeft, Home, LockKeyhole, ServerCrash } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { AppLogo } from '@/components/common/app-logo'
import { Skeleton } from '@/components/ui/skeleton'
import { usePageTitle } from '@/hooks/use-page-title'

function ErrorShell({code,title,description,icon}:{code:string;title:string;description:string;icon:React.ReactNode}){return <div className="flex min-h-screen items-center justify-center bg-slate-50 px-5 dark:bg-slate-950"><div className="w-full max-w-xl text-center"><div className="flex justify-center"><AppLogo/></div><div className="mx-auto mt-12 grid size-20 place-items-center rounded-3xl bg-brand-50 text-brand-600 dark:bg-brand-950/30">{icon}</div><div className="mt-8 text-sm font-bold uppercase tracking-[.2em] text-brand-600">Error {code}</div><h1 className="mt-3 text-4xl font-bold tracking-[-.04em]">{title}</h1><p className="mx-auto mt-4 max-w-md text-base leading-7 text-slate-500">{description}</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Button asChild><Link to="/dashboard"><Home className="size-4"/>Go to dashboard</Link></Button><Button variant="secondary" onClick={()=>history.back()}><ArrowLeft className="size-4"/>Go back</Button></div></div></div>}
export function NotFoundPage(){usePageTitle('Page not found');return <ErrorShell code="404" title="This page is out of flow" description="The route may have moved, or you may not have access to this workspace resource." icon={<AlertTriangle className="size-9"/>}/>}
export function ServerErrorPage(){usePageTitle('Server error');return <ErrorShell code="500" title="Something interrupted the flow" description="The mock server state encountered an unexpected problem. Retry or return to the dashboard." icon={<ServerCrash className="size-9"/>}/>}
export function UnauthorizedPage(){usePageTitle('Unauthorized');return <ErrorShell code="401" title="Authentication required" description="Sign in with a valid TradeFlow account to access this enterprise resource." icon={<LockKeyhole className="size-9"/>}/>}
export function ForbiddenPage(){usePageTitle('Forbidden');return <ErrorShell code="403" title="You do not have permission" description="Your current role cannot access this module. Contact a workspace administrator for access." icon={<LockKeyhole className="size-9"/>}/>}
export function FullPageLoading(){usePageTitle('Loading');return <div className="min-h-screen bg-slate-50 p-5 dark:bg-slate-950"><div className="mx-auto max-w-[1500px]"><div className="flex h-14 items-center justify-between"><Skeleton className="h-9 w-32"/><Skeleton className="h-9 w-56"/></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:4}).map((_,i)=><Skeleton key={i} className="h-36"/>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Skeleton className="h-96"/><Skeleton className="h-96"/></div></div></div>}
