import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Building2, CheckCircle2, KeyRound, MailCheck, ShieldCheck, UserCog } from 'lucide-react'
import { motion } from 'framer-motion'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card } from '@/components/ui/card'
import { usePageTitle } from '@/hooks/use-page-title'

const configs = {
  'forgot-password': { title: 'Reset your password', description: 'Enter your work email and we will send a secure reset link.', icon: KeyRound, input: 'email', button: 'Send reset link' },
  'reset-password': { title: 'Choose a new password', description: 'Create a strong password for your TradeFlow account.', icon: ShieldCheck, input: 'password', button: 'Update password' },
  'email-verification': { title: 'Verify your email', description: 'We sent a verification link to alex@tradeflow.dev.', icon: MailCheck, input: null, button: 'I have verified my email' },
  'otp-verification': { title: 'Enter verification code', description: 'Enter the six-digit code sent to your registered device.', icon: ShieldCheck, input: 'otp', button: 'Verify code' },
} as const

export function AuthUtilityPage({ type }: { type: keyof typeof configs }) { const config = configs[type]; const [done, setDone] = useState(false); const Icon = config.icon; usePageTitle(config.title); return <div>{done ? <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="text-center"><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-emerald-50 text-emerald-600 dark:bg-emerald-950/30"><CheckCircle2 className="size-8"/></div><h1 className="mt-6 text-2xl font-bold">You are all set</h1><p className="mt-2 text-sm leading-6 text-slate-500">The mock authentication step completed successfully.</p><Button asChild className="mt-7"><Link to="/auth/login">Continue to sign in<ArrowRight className="size-4"/></Link></Button></motion.div> : <><div className="grid size-12 place-items-center rounded-2xl bg-brand-50 text-brand-600 dark:bg-brand-950/30"><Icon className="size-6"/></div><h1 className="mt-6 text-3xl font-bold tracking-[-.035em]">{config.title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{config.description}</p><form onSubmit={(event) => { event.preventDefault(); setDone(true) }} className="mt-8 space-y-5">{config.input === 'email' && <div className="space-y-2"><Label>Email address</Label><Input type="email" defaultValue="alex@tradeflow.dev"/></div>}{config.input === 'password' && <><div className="space-y-2"><Label>New password</Label><Input type="password" defaultValue="password123"/></div><div className="space-y-2"><Label>Confirm password</Label><Input type="password" defaultValue="password123"/></div></>}{config.input === 'otp' && <div className="grid grid-cols-6 gap-2">{Array.from({length:6}).map((_,i) => <Input key={i} maxLength={1} inputMode="numeric" className="px-0 text-center text-lg font-bold" defaultValue={i+1}/>)}</div>}<Button type="submit" size="lg" className="w-full">{config.button}<ArrowRight className="size-4"/></Button></form><Link to="/auth/login" className="mt-6 flex items-center justify-center gap-2 text-sm font-semibold text-slate-500 hover:text-brand-600"><ArrowLeft className="size-4"/>Back to sign in</Link></>}</div> }

export function SelectionPage({ mode }: { mode: 'role' | 'tenant' }) { const navigate = useNavigate(); const roles = [{title:'Administrator',description:'Manage the full workspace and access controls',icon:UserCog},{title:'Operations manager',description:'Run inventory, orders, shipping, and suppliers',icon:ShieldCheck},{title:'Vendor operator',description:'Manage catalog, fulfillment, and payouts',icon:Building2}]; const tenants = [{title:'TradeFlow Global',description:'Primary enterprise workspace',icon:Building2},{title:'North America Operations',description:'Regional operations workspace',icon:Building2},{title:'Marketplace Sandbox',description:'Demo vendor and commerce tenant',icon:Building2}]; const items = mode === 'role' ? roles : tenants; usePageTitle(mode === 'role' ? 'Select role' : 'Select tenant'); return <div><h1 className="text-3xl font-bold tracking-[-.035em]">Select your {mode}</h1><p className="mt-2 text-sm leading-6 text-slate-500">This mock step demonstrates multi-role and multi-tenant authentication flow.</p><div className="mt-8 space-y-3">{items.map((item,index) => <button key={item.title} onClick={() => navigate(mode === 'role' ? '/auth/tenant-selection' : '/dashboard')} className={`group flex w-full items-center gap-4 rounded-2xl border p-4 text-left transition hover:-translate-y-0.5 hover:border-brand-300 hover:shadow-soft ${index===0?'border-brand-300 bg-brand-50/60 dark:bg-brand-950/20':'border-slate-200 dark:border-slate-800'}`}><div className="grid size-11 place-items-center rounded-xl bg-white text-brand-600 shadow-sm dark:bg-slate-900"><item.icon className="size-5"/></div><div className="flex-1"><div className="font-semibold">{item.title}</div><div className="mt-1 text-xs leading-5 text-slate-500">{item.description}</div></div><ArrowRight className="size-4 text-slate-300 transition group-hover:translate-x-1 group-hover:text-brand-600"/></button>)}</div></div> }
