import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Download, Upload } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { apiClient } from '@/api/client'
import { PageHeader } from '@/components/common/page-header'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { usePageTitle } from '@/hooks/use-page-title'

type Category={id:string;name:string;slug:string;parentId?:string;_count:{products:number}}
type Product={id:string;name:string}
type Variant={id:string;sku:string;name:string;options:Record<string,string>;price?:number}
type Warehouse={id:string;name:string}
type Image={id:string;url:string;isPrimary:boolean}
type Preview={total:number;valid:number;rows:Array<{row:number;data:Record<string,string>;errors:string[]}>}

export default function CatalogAdmin(){
 usePageTitle('Каталогийн удирдлага');const qc=useQueryClient();const[productId,setProductId]=useState('');const[message,setMessage]=useState('');const[preview,setPreview]=useState<Preview>()
 const categories=useQuery({queryKey:['catalog','categories'],queryFn:async()=>(await apiClient.get<Category[]>('/catalog/categories')).data})
 const products=useQuery({queryKey:['marketplace-catalog'],queryFn:async()=>(await apiClient.get<Product[]>('/products')).data})
 const variants=useQuery({queryKey:['catalog','variants',productId],enabled:!!productId,queryFn:async()=>(await apiClient.get<Variant[]>(`/catalog/products/${productId}/variants`)).data})
 const warehouses=useQuery({queryKey:['inventory','warehouses'],queryFn:async()=>(await apiClient.get<Warehouse[]>('/inventory/warehouses')).data})
 const images=useQuery({queryKey:['catalog','images',productId],enabled:!!productId,queryFn:async()=>(await apiClient.get<Image[]>(`/catalog/products/${productId}/images`)).data})
 const addCategory=useMutation({mutationFn:(body:unknown)=>apiClient.post('/catalog/categories',body),onSuccess:()=>categories.refetch()})
 const submitCategory=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);addCategory.mutate({name:d.get('name'),slug:d.get('slug'),parentId:d.get('parentId')||null});e.currentTarget.reset()}
 const submitVariant=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),options=Object.fromEntries(String(d.get('options')).split(',').map(v=>v.split('=').map(x=>x.trim())).filter(v=>v.length===2));const{data:v}=await apiClient.post<Variant>(`/catalog/products/${productId}/variants`,{name:d.get('name'),sku:d.get('sku'),barcode:d.get('barcode')||undefined,price:d.get('price')?Number(d.get('price')):undefined,options});const stock=Number(d.get('initialStock')||0),warehouseId=String(d.get('warehouseId')||'');if(stock&&warehouseId)await apiClient.post('/inventory/adjustments',{productId,variantId:v.id,warehouseId,quantity:stock,reason:'Variant initial stock'});setMessage('Хувилбар амжилттай нэмэгдлээ.');await variants.refetch();e.currentTarget.reset()}
 const importFile=async(file?:File)=>{if(!file)return;const form=new FormData();form.append('file',file);try{setPreview((await apiClient.post<Preview>('/catalog/import/preview',form)).data);setMessage('Файлыг шалгалаа.')}catch{setMessage('CSV/XLSX файлыг уншиж чадсангүй.')}}
 const confirmImport=async()=>{if(!preview||preview.valid!==preview.total)return;const{data}=await apiClient.post<{imported:number}>('/catalog/import',preview.rows.map(r=>r.data));setMessage(`${data.imported} бараа импортлогдлоо.`);setPreview(undefined);await qc.invalidateQueries()}
 const exportCsv=async()=>{const r=await apiClient.get('/catalog/export.csv',{responseType:'blob'}),url=URL.createObjectURL(r.data as Blob),a=document.createElement('a');a.href=url;a.download='tradeflow-products.csv';a.click();URL.revokeObjectURL(url)}
 const uploadImage=async(file?:File)=>{if(!file||!productId)return;const form=new FormData();form.append('image',file);const{data}=await apiClient.post<{url:string;publicId?:string}>('/upload',form);await apiClient.post(`/catalog/products/${productId}/images`,data);await images.refetch()}
 const reorder=async(ids:string[],primaryId:string)=>{await apiClient.put(`/catalog/products/${productId}/images/reorder`,{imageIds:ids,primaryId});await images.refetch()}
 const tree=(parentId?:string,level=0):React.ReactNode=>categories.data?.filter(x=>(x.parentId??undefined)===parentId).map(x=><div key={x.id} draggable onDragStart={e=>e.dataTransfer.setData('categoryId',x.id)} onDragOver={e=>e.preventDefault()} onDrop={async e=>{e.preventDefault();const id=e.dataTransfer.getData('categoryId');if(id&&id!==x.id){await apiClient.patch(`/catalog/categories/${id}`,{parentId:x.id});await categories.refetch()}}}><div className="border-b p-3" style={{paddingLeft:12+level*24}}><b>{x.name}</b><span className="ml-2 text-xs text-slate-500">/{x.slug} · {x._count.products} бараа · чирж зөөнө</span></div>{tree(x.id,level+1)}</div>)
 return <><PageHeader eyebrow="FR-2" title="Каталогийн удирдлага" description="Ангилал, хувилбар, зураг болон CSV/XLSX импорт." actions={<><Button variant="secondary" onClick={()=>void exportCsv()}><Download className="size-4"/>Экспорт</Button><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white"><Upload className="size-4"/>Импорт<input hidden type="file" accept=".csv,.xlsx" onChange={e=>void importFile(e.target.files?.[0])}/></label></>}/>
 {message&&<div className="mb-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}
 {preview&&<Card className="mb-6"><div className="flex items-center justify-between border-b p-4"><div><b>Импортын preview</b><p className="text-xs">Нийт {preview.total}, зөв {preview.valid}, алдаатай {preview.total-preview.valid}</p></div><Button disabled={preview.valid!==preview.total} onClick={()=>void confirmImport()}>Импорт батлах</Button></div><div className="max-h-56 overflow-auto">{preview.rows.map(r=><div key={r.row} className={`border-b p-2 text-xs ${r.errors.length?'bg-red-50 text-red-700':''}`}>Мөр {r.row}: {r.data.name||'-'} {r.errors.join(' · ')}</div>)}</div></Card>}
 <div className="grid gap-6 xl:grid-cols-2"><div className="space-y-5"><Card className="p-5"><h2 className="font-bold">Ангилал нэмэх</h2><form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={submitCategory}><Input name="name" required placeholder="Нэр"/><Input name="slug" required pattern="[a-z0-9-]+" placeholder="slug"/><select name="parentId" className="h-10 rounded-xl border px-3 sm:col-span-2"><option value="">Үндсэн ангилал</option>{categories.data?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Button className="sm:col-span-2">Нэмэх</Button></form></Card><Card><div className="border-b p-4 font-bold">Ангиллын мод</div>{tree()}</Card></div>
 <div className="space-y-5"><Card className="p-5"><h2 className="font-bold">Бараа ба хувилбар</h2><select className="mt-3 h-10 w-full rounded-xl border px-3" value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Бараа сонгох</option>{products.data?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{productId&&<form className="mt-3 space-y-3" onSubmit={submitVariant}><Input name="name" required placeholder="Хувилбарын нэр"/><Input name="sku" required placeholder="SKU"/><Input name="barcode" placeholder="Barcode scanner input"/><Input name="options" required placeholder="size=500ml,color=red"/><Input name="price" type="number" min="0.01" step="0.01" placeholder="Тусгай үнэ"/><select name="warehouseId" className="h-10 w-full rounded-xl border px-3"><option value="">Агуулах</option>{warehouses.data?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Input name="initialStock" type="number" min="0" defaultValue="0"/><Button className="w-full">Хувилбар нэмэх</Button></form>}</Card>
 <Card><div className="border-b p-4 font-bold">Хувилбарууд</div>{variants.data?.map(v=><div key={v.id} className="border-b p-3">{v.name} · {v.sku}{v.price?` · ${v.price.toLocaleString()}₮`:''}</div>)}</Card>
 {productId&&<Card className="p-5"><div className="flex justify-between"><b>Олон зураг</b><label className="cursor-pointer text-sm text-emerald-700">Зураг нэмэх<input hidden type="file" accept="image/*" onChange={e=>void uploadImage(e.target.files?.[0])}/></label></div><div className="mt-3 grid grid-cols-2 gap-3">{images.data?.map((img,index)=><div key={img.id} draggable onDragStart={e=>e.dataTransfer.setData('imageId',img.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const source=e.dataTransfer.getData('imageId'),ids=images.data!.map(x=>x.id),from=ids.indexOf(source);if(from>=0){ids.splice(from,1);ids.splice(index,0,source);void reorder(ids,images.data!.find(x=>x.isPrimary)?.id??ids[0]!)}}} className="rounded-xl border p-2"><img src={img.url} className="h-28 w-full rounded-lg object-cover"/><div className="mt-2 flex gap-2"><Button size="sm" variant={img.isPrimary?'default':'secondary'} onClick={()=>void reorder(images.data!.map(x=>x.id),img.id)}>Үндсэн</Button><Button size="sm" variant="secondary" onClick={async()=>{await apiClient.delete(`/catalog/images/${img.id}`);await images.refetch()}}>Устгах</Button></div></div>)}</div></Card>}</div></div></>
}
