import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { PackageCheck, Truck } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { apiClient } from '@/api/client'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { PageHeader } from '@/components/common/page-header'

type Order={id:string;orderNumber:string;status:string;recipientName:string;items:Array<{id:string;quantity:number;product:{name:string}}>} 
type Picking={orderId:string;orderNumber:string;lines:Array<{productId:string;product:string;quantity:number;warehouseId?:string;suggestedBatches:Array<{id:string;batchNumber:string;expiresAt?:string;quantity:number}>}>}
export default function Fulfillment(){const [orderId,setOrderId]=useState(''),client=useQueryClient();const orders=useQuery({queryKey:['orders'],queryFn:async()=>(await apiClient.get<Order[]>('/orders')).data});const picking=useQuery({queryKey:['picking',orderId],enabled:Boolean(orderId),queryFn:async()=>(await apiClient.get<Picking>(`/fulfillment/picking/${orderId}`)).data});const ship=useMutation({mutationFn:async(body:unknown)=>apiClient.post('/fulfillment/shipments',body),onSuccess:async()=>{await client.invalidateQueries();setOrderId('')}});const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);ship.mutate({orderId,carrierName:d.get('carrierName'),trackingCode:d.get('trackingCode'),lines:picking.data?.lines.map(row=>({productId:row.productId,quantity:row.quantity}))})};return <><PageHeader eyebrow="FR-7" title="Picking ба packing" description="Нөөцлөгдсөн захиалгыг FEFO batch саналын дагуу бэлтгэж, tracking code-той shipment болгоно."/><div className="grid gap-6 xl:grid-cols-[380px_1fr]"><Card className="overflow-hidden"><div className="border-b p-5 font-bold">Бэлтгэх захиалгууд</div><div className="max-h-[600px] divide-y overflow-auto">{orders.data?.filter(row=>!['SHIPPED','DELIVERED','CANCELLED'].includes(row.status)).map(row=><button key={row.id} onClick={()=>setOrderId(row.id)} className={`w-full p-4 text-left ${orderId===row.id?'bg-emerald-50':''}`}><div className="font-bold">{row.orderNumber}</div><div className="text-xs text-slate-500">{row.recipientName} · {row.status} · {row.items.length} мөр</div></button>)}</div></Card><Card className="p-6">{picking.data?<><div className="flex items-center gap-3"><PackageCheck className="size-7 text-emerald-600"/><div><h2 className="text-xl font-bold">{picking.data.orderNumber}</h2><p className="text-sm text-slate-500">Picking list</p></div></div><div className="mt-5 space-y-3">{picking.data.lines.map(row=><div key={row.productId} className="rounded-2xl border p-4"><div className="flex justify-between"><div className="font-semibold">{row.product}</div><div className="font-bold">{row.quantity} ш</div></div>{row.suggestedBatches.length>0&&<div className="mt-2 text-xs text-amber-700">FEFO: {row.suggestedBatches.map(batch=>`${batch.batchNumber} (${batch.expiresAt?new Date(batch.expiresAt).toLocaleDateString('mn-MN'):'хугацаагүй'})`).join(', ')}</div>}</div>)}</div><form onSubmit={submit} className="mt-6 grid gap-3 sm:grid-cols-2"><Input name="carrierName" placeholder="Тээврийн компани"/><Input name="trackingCode" required placeholder="Ачааны дугаар"/><Button className="sm:col-span-2" loading={ship.isPending}><Truck className="size-4"/>Packing дуусгаж, хүргэлтэнд гаргах</Button></form></>:<div className="grid min-h-72 place-items-center text-slate-400">Захиалга сонгоно уу.</div>}</Card></div></>}
