import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, Trash2 } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { apiClient } from '@/api/client'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { PageHeader } from '@/components/common/page-header'

type Product = { id: string; name: string; price: number; stock: number }
type Customer = { id: string; name: string; phone?: string; groupCode?: string; creditLimit: number; creditUsed: number }
type Line = { productId: string; quantity: number }
export default function ManualOrder() {
  const [channel,setChannel]=useState<'MANUAL'|'B2B'>('MANUAL'), [lines,setLines]=useState<Line[]>([{productId:'',quantity:1}]), [message,setMessage]=useState(''), client=useQueryClient()
  const products=useQuery({queryKey:['marketplace-catalog'],queryFn:async()=>(await apiClient.get<Product[]>('/products')).data})
  const customers=useQuery({queryKey:['b2b','customers'],queryFn:async()=>(await apiClient.get<Customer[]>('/b2b/customers')).data})
  const create=useMutation({mutationFn:async(body:unknown)=>(await apiClient.post<{orderNumber:string}>('/orders',body)).data,onSuccess:async(row)=>{setMessage(`${row.orderNumber} захиалга үүслээ.`);setLines([{productId:'',quantity:1}]);await client.invalidateQueries()},onError:()=>setMessage('Захиалга үүссэнгүй. Нөөц болон зээлийн хязгаарыг шалгана уу.')})
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);create.mutate({channel,customerId:data.get('customerId')||undefined,recipientName:data.get('recipientName'),phone:data.get('phone'),city:data.get('city'),district:data.get('district'),address:data.get('address'),items:lines})}
  return <><PageHeader eyebrow="FR-6.2 / FR-6.3" title="Manual болон B2B захиалга" description="Нэг price resolver, credit limit, stock reservation ашиглан олон мөртэй захиалга үүсгэнэ." />{message&&<div className="mb-5 rounded-2xl bg-emerald-50 p-4 font-semibold text-emerald-700">{message}</div>}<form onSubmit={submit} className="grid gap-6 xl:grid-cols-[1fr_1.2fr]"><Card className="p-6"><h2 className="font-bold">Харилцагч ба хүргэлт</h2><div className="mt-4 space-y-3"><select value={channel} onChange={e=>setChannel(e.target.value as 'MANUAL'|'B2B')} className="h-10 w-full rounded-xl border bg-transparent px-3"><option value="MANUAL">Гар захиалга</option><option value="B2B">B2B гэрээт захиалга</option></select><select name="customerId" required={channel==='B2B'} className="h-10 w-full rounded-xl border bg-transparent px-3"><option value="">Харилцагч сонгох</option>{customers.data?.map(row=><option key={row.id} value={row.id}>{row.name} · боломжит зээл {Number(row.creditLimit)-Number(row.creditUsed)}</option>)}</select><Input name="recipientName" required placeholder="Хүлээн авагч"/><Input name="phone" required minLength={8} placeholder="Утас"/><Input name="city" required placeholder="Хот"/><Input name="district" required placeholder="Дүүрэг"/><Input name="address" required placeholder="Дэлгэрэнгүй хаяг"/></div></Card><Card className="p-6"><div className="flex items-center justify-between"><h2 className="font-bold">Захиалгын мөрүүд</h2><Button type="button" size="sm" variant="secondary" onClick={()=>setLines(rows=>[...rows,{productId:'',quantity:1}])}><Plus className="size-4"/>Мөр нэмэх</Button></div><div className="mt-4 space-y-3">{lines.map((line,index)=><div key={index} className="grid grid-cols-[1fr_100px_40px] gap-2"><select required value={line.productId} onChange={e=>setLines(rows=>rows.map((row,i)=>i===index?{...row,productId:e.target.value}:row))} className="h-10 rounded-xl border bg-transparent px-3"><option value="">Бараа сонгох</option>{products.data?.map(row=><option key={row.id} value={row.id}>{row.name} · {row.price}₮ · үлдэгдэл {row.stock}</option>)}</select><Input type="number" min={1} value={line.quantity} onChange={e=>setLines(rows=>rows.map((row,i)=>i===index?{...row,quantity:Number(e.target.value)}:row))}/><Button type="button" size="icon" variant="ghost" disabled={lines.length===1} onClick={()=>setLines(rows=>rows.filter((_,i)=>i!==index))}><Trash2 className="size-4"/></Button></div>)}</div><Button className="mt-6 w-full" loading={create.isPending}>Захиалга үүсгэх</Button></Card></form></>
}
