import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import axios from 'axios'
import { Check, Download, RefreshCw } from 'lucide-react'
import { type FormEvent, useState } from 'react'
import { apiClient } from '@/api/client'
import { PageHeader } from '@/components/common/page-header'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { useAuth } from '@/contexts/auth-context'
import { usePageTitle } from '@/hooks/use-page-title'

type Tenant = { id: string; name: string; slug: string; domain?: string; domainVerifiedAt?: string; subscription: string; active: boolean }
type Usage = { tenant: Tenant; usage: { users: number; products: number; warehouses: number }; limits: { users: number; products: number; warehouses: number } }
type Health = { tenants: number; activeTenants: number; users: number; products: number; orders: number; memoryMb: number; uptimeSeconds: number; queue: { running: boolean } }
type Incident = { id: string; severity: string; source: string; title: string; acknowledged: boolean; resolvedAt?: string; createdAt: string }
const errorMessage = (error: unknown) => axios.isAxiosError(error) ? String(error.response?.data?.message ?? error.message) : 'Үйлдэл амжилтгүй боллоо.'

export default function PlatformAdmin() {
  usePageTitle('Платформын удирдлага')
  const { user } = useAuth()
  const client = useQueryClient()
  const enabled = Boolean(user?.platformAdmin)
  const [dns, setDns] = useState('')
  const [notice, setNotice] = useState('')
  const health = useQuery({ queryKey: ['platform', 'health'], enabled, refetchInterval: 30000, queryFn: async () => (await apiClient.get<Health>('/admin/platform/health')).data })
  const usage = useQuery({ queryKey: ['platform', 'usage'], enabled, queryFn: async () => (await apiClient.get<Usage[]>('/admin/platform/usage')).data })
  const incidents = useQuery({ queryKey: ['platform', 'incidents'], enabled, refetchInterval: 30000, queryFn: async () => (await apiClient.get<{ incidents: Incident[] }>('/admin/platform/incidents')).data.incidents })
  const create = useMutation({ mutationFn: (body: unknown) => apiClient.post('/admin/platform/tenants', body), onSuccess: async () => { setNotice('Tenant амжилттай үүслээ.'); await client.invalidateQueries({ queryKey: ['platform'] }) } })
  const action = useMutation({ mutationFn: async ({ url, body, method = 'post' }: { url: string; body?: unknown; method?: 'post' | 'patch' }) => apiClient.request({ url, method, data: body }), onSuccess: async () => client.invalidateQueries({ queryKey: ['platform'] }) })
  const failed = health.error ?? usage.error ?? incidents.error ?? create.error ?? action.error
  const refresh = () => void Promise.all([health.refetch(), usage.refetch(), incidents.refetch()])
  const domain = async (id: string, operation: 'request' | 'verify' | 'attach') => { try { const { data } = await apiClient.post(`/admin/platform/tenants/${id}/domain/${operation}`); if (data?.value) setDns(`${data.name} TXT ${data.value}`); setNotice(operation === 'verify' ? 'Domain баталгаажлаа.' : 'Domain үйлдэл амжилттай.'); await client.invalidateQueries({ queryKey: ['platform'] }) } catch (error) { setNotice(errorMessage(error)) } }
  const exportTenant = async (id: string) => { const downloadWindow = window.open('', '_blank'); try { const { data } = await apiClient.post<{ downloadUrl: string }>(`/admin/platform/tenants/${id}/export`); const origin = new URL(apiClient.defaults.baseURL ?? window.location.origin).origin; if (downloadWindow) downloadWindow.location.href = `${origin}${data.downloadUrl}`; else window.location.assign(`${origin}${data.downloadUrl}`); setNotice('Export файл бэлтгэгдлээ.') } catch (error) { downloadWindow?.close(); setNotice(errorMessage(error)) } }
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); create.mutate({ name: data.get('name'), slug: data.get('slug'), domain: data.get('domain') || undefined, primaryColor: '#059669' }, { onSuccess: () => form.reset() }) }

  if (!enabled) return <div className="space-y-5"><PageHeader eyebrow="Платформ" title="Платформын удирдлага" description="Tenant болон системийн төлөв." /><Card className="border-amber-200 bg-amber-50 p-8 text-amber-900">Энэ хэсэгт Platform Admin эрх шаардлагатай.</Card></div>
  const stats = [['Tenant', health.data?.tenants], ['Идэвхтэй', health.data?.activeTenants], ['Хэрэглэгч', health.data?.users], ['Бараа', health.data?.products], ['Захиалга', health.data?.orders], ['Memory MB', health.data?.memoryMb], ['Queue', health.data?.queue?.running ? 'Ажиллаж байна' : 'Зогссон']]
  return <div className="space-y-6">
    <PageHeader eyebrow="Платформ" title="Платформын эрүүл мэнд ба tenant удирдлага" description="Ашиглалт, багц, domain, export, suspend болон incident удирдлага." actions={<Button variant="secondary" onClick={refresh}><RefreshCw className="size-4" />Шинэчлэх</Button>} />
    {notice && <Card className="border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">{notice}</Card>}
    {failed && <Card className="border-red-200 bg-red-50 p-4 text-sm text-red-700">{errorMessage(failed)}</Card>}
    <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-7">{stats.map(([label, value]) => <Card key={String(label)} className="p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-xl font-bold">{health.isLoading ? '…' : value ?? 0}</div></Card>)}</div>
    <Card className="p-5"><b>Tenant үүсгэх</b><form onSubmit={submit} className="mt-3 grid gap-3 md:grid-cols-4"><Input name="name" required minLength={2} placeholder="Нэр" /><Input name="slug" required pattern="[a-z0-9-]+" placeholder="slug" /><Input name="domain" placeholder="shop.example.mn" /><Button loading={create.isPending} disabled={create.isPending}>Үүсгэх</Button></form></Card>
    {dns && <Card className="flex flex-col gap-2 border-amber-200 bg-amber-50 p-4 text-sm sm:flex-row sm:items-center"><span className="flex-1 font-mono">DNS дээр нэмнэ: {dns}</span><Button size="sm" variant="secondary" onClick={() => void navigator.clipboard.writeText(dns)}>Хуулах</Button></Card>}
    <Card className="overflow-auto"><table className="w-full min-w-[1200px] text-sm"><thead><tr className="border-b bg-slate-50 dark:bg-slate-900"><th className="p-3 text-left">Tenant</th><th>Plan</th><th>Users</th><th>Products</th><th>Warehouses</th><th>Domain</th><th>Үйлдэл</th></tr></thead><tbody>{usage.isLoading ? <tr><td colSpan={7} className="p-10 text-center text-slate-500">Tenant мэдээлэл уншиж байна...</td></tr> : !usage.data?.length ? <tr><td colSpan={7} className="p-10 text-center text-slate-500">Tenant алга.</td></tr> : usage.data.map((row) => <tr key={row.tenant.id} className="border-b"><td className="p-3 font-bold">{row.tenant.name}<div className={row.tenant.active ? 'text-emerald-600' : 'text-rose-600'}>{row.tenant.active ? 'Идэвхтэй' : 'Түдгэлзсэн'}</div></td><td><select value={row.tenant.subscription} disabled={action.isPending} onChange={(event) => action.mutate({ url: `/admin/platform/tenants/${row.tenant.id}/plan`, body: { plan: event.target.value, reason: 'Platform admin plan change' } })} className="rounded border bg-transparent p-2"><option>MVP</option><option>GROWTH</option><option>ENTERPRISE</option></select></td><td className="text-center">{row.usage.users}/{row.limits.users}</td><td className="text-center">{row.usage.products}/{row.limits.products}</td><td className="text-center">{row.usage.warehouses}/{row.limits.warehouses}</td><td className="px-2">{row.tenant.domain ?? '-'}<div className="text-xs text-slate-500">{row.tenant.domainVerifiedAt ? 'Батлагдсан' : 'Баталгаажаагүй'}</div></td><td><div className="flex flex-wrap gap-1"><Button size="sm" variant="secondary" onClick={() => void domain(row.tenant.id, 'request')}>TXT</Button><Button size="sm" variant="secondary" onClick={() => void domain(row.tenant.id, 'verify')}>Шалгах</Button>{row.tenant.domainVerifiedAt && <Button size="sm" variant="secondary" onClick={() => void domain(row.tenant.id, 'attach')}>Attach</Button>}<Button size="sm" variant="secondary" onClick={() => void exportTenant(row.tenant.id)}><Download className="size-4" />Export</Button><Button size="sm" variant={row.tenant.active ? 'destructive' : 'default'} onClick={() => { if (window.confirm(row.tenant.active ? 'Tenant-ийг түдгэлзүүлэх үү?' : 'Tenant-ийг идэвхжүүлэх үү?')) action.mutate({ url: `/admin/platform/tenants/${row.tenant.id}`, method: 'patch', body: { active: !row.tenant.active } }) }}>{row.tenant.active ? 'Түдгэлзүүлэх' : 'Идэвхжүүлэх'}</Button></div></td></tr>)}</tbody></table></Card>
    <Card><div className="border-b p-4 font-bold">Incident ба worker</div>{incidents.isLoading ? <div className="p-6 text-slate-500">Уншиж байна...</div> : incidents.data?.length ? incidents.data.map((incident) => <div key={incident.id} className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center"><div className="flex-1"><b className={incident.severity === 'critical' ? 'text-red-600' : 'text-amber-600'}>{incident.severity.toUpperCase()}</b> · {incident.title}<div className="text-xs text-slate-500">{incident.source} · {new Date(incident.createdAt).toLocaleString('mn-MN')}</div></div>{incident.acknowledged ? <span className="flex items-center gap-1 text-sm text-emerald-600"><Check className="size-4" />Хүлээн авсан</span> : <Button size="sm" variant="secondary" onClick={() => action.mutate({ url: `/admin/platform/incidents/${incident.id}`, method: 'patch', body: { acknowledged: true } })}>Хүлээн авах</Button>}{!incident.resolvedAt && <Button size="sm" onClick={() => action.mutate({ url: `/admin/platform/incidents/${incident.id}`, method: 'patch', body: { resolved: true } })}>Шийдвэрлэсэн</Button>}</div>) : <div className="p-6 text-slate-500">Incident алга.</div>}</Card>
  </div>
}
